replicaCount: 4

ingress:
  enabled: true
  host: myapp.prod.com

resources:
  requests:
    cpu: "300m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

autoscaling:
  minReplicas: 4
  maxReplicas: 20
